# Temporary import blocks for DNS zone VNet links that exist in Azure
# but are missing from Terraform state due to azapi polling race condition.
# Uses azapi identity-based import (bypasses broken ImportState method).
# Remove this file after a successful apply.

locals {
  _dns_zone_imports = {
    azure_acr_registry                  = "privatelink.azurecr.io"
    azure_ai_cog_svcs                   = "privatelink.cognitiveservices.azure.com"
    azure_ai_oai                        = "privatelink.openai.azure.com"
    azure_ai_services                   = "privatelink.services.ai.azure.com"
    azure_aks_mgmt                      = "privatelink.canadacentral.azmk8s.io"
    azure_api_management                = "privatelink.azure-api.net"
    azure_app_configuration             = "privatelink.azconfig.io"
    azure_app_service                   = "privatelink.azurewebsites.net"
    azure_arc_guest_configuration       = "privatelink.guestconfiguration.azure.com"
    azure_arc_hybrid_compute            = "privatelink.his.arc.azure.com"
    azure_arc_kubernetes                = "privatelink.dp.kubernetesconfiguration.azure.com"
    azure_attestation                   = "privatelink.attest.azure.net"
    azure_automation                    = "privatelink.azure-automation.net"
    azure_avd_feed_mgmt                 = "privatelink.wvd.microsoft.com"
    azure_avd_global                    = "privatelink-global.wvd.microsoft.com"
    azure_backup                        = "privatelink.cnc.backup.windowsazure.com"
    azure_batch                         = "privatelink.batch.azure.com"
    azure_bot_svc_bot                   = "privatelink.directline.botframework.com"
    azure_bot_svc_token                 = "privatelink.token.botframework.com"
    azure_container_apps                = "privatelink.canadacentral.azurecontainerapps.io"
    azure_cosmos_db_analytical          = "privatelink.analytics.cosmos.azure.com"
    azure_cosmos_db_cassandra           = "privatelink.cassandra.cosmos.azure.com"
    azure_cosmos_db_gremlin             = "privatelink.gremlin.cosmos.azure.com"
    azure_cosmos_db_mongo               = "privatelink.mongo.cosmos.azure.com"
    azure_cosmos_db_mongo_vcore         = "privatelink.mongocluster.cosmos.azure.com"
    azure_cosmos_db_postgres            = "privatelink.postgres.cosmos.azure.com"
    azure_cosmos_db_sql                 = "privatelink.documents.azure.com"
    azure_cosmos_db_table               = "privatelink.table.cosmos.azure.com"
    azure_data_explorer                 = "privatelink.canadacentral.kusto.windows.net"
    azure_data_factory                  = "privatelink.datafactory.azure.net"
    azure_data_factory_portal           = "privatelink.adf.azure.com"
    azure_data_lake_gen2                = "privatelink.dfs.core.windows.net"
    azure_databricks_ui_api             = "privatelink.azuredatabricks.net"
    azure_digital_twins                 = "privatelink.digitaltwins.azure.net"
    azure_event_grid                    = "privatelink.eventgrid.azure.net"
    azure_event_grid_mqtt               = "privatelink.ts.eventgrid.azure.net"
    azure_fabric                        = "privatelink.fabric.microsoft.com"
    azure_file_sync                     = "privatelink.afs.azure.net"
    azure_grafana                       = "privatelink.grafana.azure.com"
    azure_hdinsight                     = "privatelink.azurehdinsight.net"
    azure_healthcare                    = "privatelink.azurehealthcareapis.com"
    azure_healthcare_dicom              = "privatelink.dicom.azurehealthcareapis.com"
    azure_iot_central                   = "privatelink.azureiotcentral.com"
    azure_iot_hub                       = "privatelink.azure-devices.net"
    azure_iot_hub_provisioning          = "privatelink.azure-devices-provisioning.net"
    azure_iot_hub_update                = "privatelink.api.adu.microsoft.com"
    azure_key_vault                     = "privatelink.vaultcore.azure.net"
    azure_log_analytics                 = "privatelink.oms.opinsights.azure.com"
    azure_log_analytics_data            = "privatelink.ods.opinsights.azure.com"
    azure_managed_hsm                   = "privatelink.managedhsm.azure.net"
    azure_managed_prometheus            = "privatelink.canadacentral.prometheus.monitor.azure.com"
    azure_managed_redis                 = "privatelink.redis.azure.net"
    azure_maria_db_server               = "privatelink.mariadb.database.azure.com"
    azure_media_services_delivery       = "privatelink.media.azure.net"
    azure_migration_service             = "privatelink.prod.migration.windowsazure.com"
    azure_ml                            = "privatelink.api.azureml.ms"
    azure_ml_notebooks                  = "privatelink.notebooks.azure.net"
    azure_monitor                       = "privatelink.monitor.azure.com"
    azure_monitor_agent                 = "privatelink.agentsvc.azure-automation.net"
    azure_mysql_db_server               = "privatelink.mysql.database.azure.com"
    azure_postgres_sql_server           = "privatelink.postgres.database.azure.com"
    azure_power_bi_dedicated            = "privatelink.pbidedicated.windows.net"
    azure_power_bi_power_query_correct  = "privatelink.prod.powerquery.microsoft.com"
    azure_power_bi_tenant_analysis      = "privatelink.analysis.windows.net"
    azure_purview_account               = "privatelink.purview.azure.com"
    azure_purview_service               = "privatelink.purview-service.microsoft.com"
    azure_purview_studio                = "privatelink.purviewstudio.azure.com"
    azure_redis_cache                   = "privatelink.redis.cache.windows.net"
    azure_redis_enterprise              = "privatelink.redisenterprise.cache.azure.net"
    azure_search                        = "privatelink.search.windows.net"
    azure_service_hub                   = "privatelink.servicebus.windows.net"
    azure_signalr_service               = "privatelink.service.signalr.net"
    azure_site_recovery                 = "privatelink.siterecovery.windowsazure.com"
    azure_sql_server                    = "privatelink.database.windows.net"
    azure_static_web_apps               = "privatelink.azurestaticapps.net"
    azure_static_web_apps_partitioned_1 = "privatelink.1.azurestaticapps.net"
    azure_static_web_apps_partitioned_2 = "privatelink.2.azurestaticapps.net"
    azure_static_web_apps_partitioned_3 = "privatelink.3.azurestaticapps.net"
    azure_static_web_apps_partitioned_4 = "privatelink.4.azurestaticapps.net"
    azure_static_web_apps_partitioned_5 = "privatelink.5.azurestaticapps.net"
    azure_storage_blob                  = "privatelink.blob.core.windows.net"
    azure_storage_file                  = "privatelink.file.core.windows.net"
    azure_storage_queue                 = "privatelink.queue.core.windows.net"
    azure_storage_table                 = "privatelink.table.core.windows.net"
    azure_storage_web                   = "privatelink.web.core.windows.net"
    azure_synapse                       = "privatelink.azuresynapse.net"
    azure_synapse_dev                   = "privatelink.dev.azuresynapse.net"
    azure_synapse_sql                   = "privatelink.sql.azuresynapse.net"
    azure_web_pubsub                    = "privatelink.webpubsub.azure.com"
  }
}

import {
  for_each = local._dns_zone_imports
  to       = module.vwan.module.private_dns_zones["cc-hub01"].module.avm_res_network_privatednszone[each.key].module.virtual_network_links["sidecar-ce-vnet"].azapi_resource.private_dns_zone_network_link
  identity = {
    type = "Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01"
    id   = "/subscriptions/e6f19bf3-8bef-4939-95dc-b7b7092ea430/resourceGroups/DNS-RG/providers/Microsoft.Network/privateDnsZones/${each.value}/virtualNetworkLinks/vnet_link-${each.key}-sidecar-ce-vnet"
  }
}
